### ISSUE TITLE
Error 404 while misp-core build

### ISSUE THREAD

**Issue by GurBal** [MISP/misp-docker#10]
Step 9/53 : ADD https://raw.githubusercontent.com/MISP/MISP/${CORE_COMMIT:-${CORE_TAG}}/app/composer.json /tmp
ERROR: Service 'misp-core' failed to build: ADD failed: failed to GET https://raw.githubusercontent.com/MISP/MISP//app/composer.json with status 404 Not Found: 404: Not Found

**Comment by ostefano** [comment]
You did not follow the README and did not create the .env file.

**Comment by GurBal** [comment]
Thanks @ostefano,

i created .env file and it threw error on step 42

Step 42/53 : COPY --from=python-build /wheels /wheels
ERROR: Service 'misp-core' failed to build: COPY failed: stat wheels: file does not exist

**Comment by ostefano** [comment]
@GurBal once again, check the README and this time follow the Troubleshooting section.

In this instance, you can delete all built images as per instructions, or also try to disable the cache (`docker-compose build --no-cache`)

**Comment by GurBal** [comment]
works fine now :) apologies for the hassle.
