### ISSUE TITLE
502 Bad Gateway; Server Settings & Maintenance Page not working

### ISSUE THREAD

**Issue by DazityGod** [MISP/misp-docker#100]
Hi,

Whenever i try to visit the Server Settings & Maintenance page, i keep getting 502 Bad Gateway. This is the only page that appears to be affected. Error logs don't seem to be very useful in trying to troubleshoot whats wrong. I have tried rebooting my server and restarting docker container multiple times don't seem to work. 

Any specific log file i can navigate to try to debug this issue?

![image](https://github.com/user-attachments/assets/a6b6b580-b2ca-4a4a-bafb-6ba4e41f196c)

**Comment by ostefano** [comment]
Ask the chat channel on Gitter/Matrix.

**Comment by AmitKulkarni9** [comment]
@DazityGod I am too getting this error. did you manage to fix this issue ?

**Comment by DazityGod** [comment]
> @DazityGod I am too getting this error. did you manage to fix this issue ?

It was my antivirus sensor blocking it....

**Comment by AmitKulkarni9** [comment]
@DazityGod oh ok... how did you figure that out :) ?

**Comment by DazityGod** [comment]
> @DazityGod oh ok... how did you figure that out :) ?

had to reprovision a new server and the moment i installed back my antivirus sensor same issue occurred.
