### ISSUE TITLE
Error on fresh build

### ISSUE THREAD

**Issue by sebdraven** [MISP/misp-docker#102]
Hi,

in the lastest image the bug described here(https://github.com/MISP/MISP/issues/9791) is present. 

I need to fix it with the command described in the issue

**Comment by ostefano** [comment]
I don't think the image is affected, most probably the first time you ran it, something prevented the runUpdates command to run successfully. Can you try to reproduce it? Otherwise I will close this.

**Comment by sebdraven** [comment]
Yes, I reproduce it three times. At each fresh installation, I need to execute cake admin command `cake admin setDatabaseVersion 60`

**Comment by ostefano** [comment]
Did you remove the MySQL volume each time? Anything in the logs during the first run? (you should see the output of runUpdates). Is the issue reflected in the diagnostic page?

**Comment by sebdraven** [comment]
Yes at each time. In the logs first run, I've  this:
```
2024-08-01 09:25:35 Error: [MissingTableException] Table bookmarks for model Bookmark was not found in datasource default.
Exception Attributes: array (
  'table' => 'bookmarks',
  'class' => 'Bookmark',
  'ds' => 'default',
)
Request URL: /users/routeafterlogin
```

**Comment by ostefano** [comment]
I still can't reproduce it.

```
root@7bbca8079e82:/var/www/MISP# MYSQLCMD="mysql -u $MYSQL_USER -p$MYSQL_PASSWORD -P $MYSQL_PORT -h $MYSQL_HOST -r -N $MYSQL_DATABASE"
root@7bbca8079e82:/var/www/MISP# echo "DESCRIBE bookmarks" | $MYSQLCMD
id	int(11)	NO	PRI	NULL	auto_increment
user_id	int(10) unsigned	NO	MUL	NULL
org_id	int(10) unsigned	NO	MUL	NULL
name	varchar(191)	NO	MUL	NULL
url	varchar(255)	NO		NULL
exposed_to_org	tinyint(1)	NO		0
root@7bbca8079e82:/var/www/MISP#
```

@UFOSmuggler any idea?

**Comment by ostefano** [comment]
Before running the `setDatabase` command, did you try running `sudo -u www-data /var/www/MISP/app/Console/cake Admin runUpdates` inside the container?

**Comment by ostefano** [comment]
So the latest MySQL dump is version 126 (see https://github.com/MISP/MISP/blob/2.4/INSTALL/MYSQL.sql).

Latest version of MISP create the `bookmark` table as part of the `127` update (see here https://github.com/MISP/MISP/blob/2.4/app/Model/AppModel.php#L2185).

So this means that for some reason the `runUpdates` command (https://github.com/MISP/misp-docker/blob/130a6ba8c08a391e13e594ff7ae89351de91d8c0/core/files/configure_misp.sh#L215) did not run succcesfully.

In my tests (clean setup, no existing DB), the bootstrap process correctly runs the command:
```
misp-core-1     | MISP | Apply DB updates ...
misp-core-1     | Executing all updates to bring the database up to date with the current version.
misp-core-1     | Executing 127.................Done
misp-core-1     | All updates completed.
```

So my question is this: what is your output?

**Comment by sebdraven** [comment]
```
Executing all updates to bring the database up to date with the current version.
All updates completed.
```

I've already fixe the pb with `cake admin setDatabaseVersion 60 `

now it works

**Comment by ostefano** [comment]
Then I am going to close this issue, because it can not be reproduced.

**Comment by UFOSmuggler** [comment]
likewise cannot reproduce
