### ISSUE TITLE
No authentication logs on filesystem - issue?

### ISSUE THREAD

**Issue by DkYSwe** [MISP/misp-docker#105]
Hi,

Currently running MISP 2.4.192 (misp-docker).
I have problems getting authentications logged to filesystem.
Only get the following files in logs/
----------------------------------------
debug.log  error.log  misp-workers-errors.log  misp-workers.log  mispzmq.error.log  mispzmq.log  server-sync.log

Enabled "MISP.log_new_audit" - I can't see any logging being done to system /var/logs either.

Any hint appreciated, need to log this to SIEM and file on filesystem would be the easiest.
(I can see all authentication logs in MISP gui).

Best Regards,
Daniel

**Comment by ostefano** [comment]
This is not an issue with the image. I would suggest to ask MISP support channels (Gitter/Matrix).
