### ISSUE TITLE
Cannot build docker because ERROR: Service 'misp-core' failed to build: COPY failed: stat wheels: file does not exist

### ISSUE THREAD

**Issue by Danouchka** [MISP/misp-docker#11]
Hello 
I cannot build the docker because I get 
tting up nginx (1.18.0-6.1+deb11u3) ...
Processing triggers for libc-bin (2.31-13+deb11u7) ...
Processing triggers for ca-certificates (20210119) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Processing triggers for php7.4-cli (7.4.33-1+deb11u4) ...
Processing triggers for php7.4-fpm (7.4.33-1+deb11u4) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Removing intermediate container f4ce4511c89c
 ---> b8f91fdc9f02
Step 42/53 : COPY --from=python-build /wheels /wheels
ERROR: Service 'misp-core' failed to build: COPY failed: stat wheels: file does not exist

Please how to debug and correct ?

**Comment by Danouchka** [comment]
My docker version
# docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by ostefano** [comment]
@Danouchka try to ignore the cache while building, i.e., `docker-compose build --no-cache`

**Comment by Danouchka** [comment]
Thank you @ostefano ! But the error still persits

**Comment by ostefano** [comment]
Interesting. I assume you created the `.env` file, right?
As a last resort, try to remove existing images/containers using the command outlined in the `Troubleshooting` section fo the readme file.

**Comment by Danouchka** [comment]
Hello 

Yes .env file was created. 
The VM was brand new (Debian on GCP Compute Linux sa-da-fleet-demo 5.10.0-27-cloud-amd64 #1 SMP Debian 5.10.205-2 (2023-12-31) x86_64 GNU/Linux ) 
There were no previous images or container running and every time I do remove all docker images

**Comment by ostefano** [comment]
That is weird, did you try the command `docker system prune -a`?
Try also the command `docker compose build` without dash.

As a last resort, try to update the docker using the link provided.
I know it should not be needed, I am just trying to understand if something is afoot.

Also, are you sure you have enough disk space available?

**Comment by Danouchka** [comment]
Hi will try 
My disk is 20GB, do you think it's not enough ? 
I will double the disk space and will let you know

**Comment by ostefano** [comment]
There is also the option `--force-recreate` that might help.

Do you have 20GB of free space or 20GB in total?
I have been burnt a couple of times already with disk space constraint.

The error you are seeing is compatible with a layer that completed building but with some non fatal errors (like disk space issues).

**Comment by Danouchka** [comment]
it was 20GB in total :-)

**Comment by Danouchka** [comment]
Indeed that works better with 40GB and docker compose , not docker compose 
I want to expose it publicly  , should I change the base URL to my FQDN ?

**Comment by ostefano** [comment]
Correct.

**Comment by Danouchka** [comment]
Hello, I changed the base URL to 'https://misp01.dyndns.org' but the CN is still localhost 
As a result I get that when connecting 
<img width="1747" alt="Capture d’écran 2024-01-08 à 14 41 21" src="https://github.com/MISP/misp-docker/assets/48563314/a242fb6b-8514-40cf-b20b-799d321367ca">

**Comment by ostefano** [comment]
This is expected because you are using self signed certificates. You need to replace them.
Also, this is not anymore a concern of this specific image. Please use gitter or other avenues to get further support.

**Comment by Danouchka** [comment]
Thank you very much for all your support. I will make out with the certificate

**Comment by ncsc-fi-kimmo** [comment]
Btw if you use the old command `docker-compose` instead of the new `docker compose` I get the same `ERROR: Service 'misp-core' failed to build: COPY failed: stat wheels: file does not exist` error. Use the new compose command.

**Comment by ostefano** [comment]
@ncsc-fi-kimmo it is because of a combination of docker-related packages installed by some distros.
