### ISSUE TITLE
[ MISP Modules ] No module for scanning attachments for viruses is currently defined.

### ISSUE THREAD

**Issue by Diogo-Rego** [MISP/misp-docker#110]
### How to configure this part of MISP Modules

* In `Security Audit`

![image](https://github.com/user-attachments/assets/754c2be6-2c5a-43f1-b5bc-19b854f01910)

* In `Attachment scan module`

![image](https://github.com/user-attachments/assets/8e0a5c32-4825-4488-8b81-03a2de1d9054)

* In `Module System`

![image](https://github.com/user-attachments/assets/050ec783-5ea4-446d-a1d6-db65ebb45f53)

**Comment by ostefano** [comment]
Ask Gitter/Matrix chat, and then if you want that module enabled, propose a PR.
I will close this because it is a non-issue
