### ISSUE TITLE
Workflow modules (Action/Logic/Misp-modules/Custom) settings are not persistent across container restarts

### ISSUE THREAD

**Issue by DaanWillems** [MISP/misp-docker#111]
Hello,

I am wanting to use the workflow feature in our containerized setup. I have enabled workflows and actions, which appear correctly in my mounted config file.

I then go into the workflows and enable certain workflow modules (In testing I enabled all of them). This works correctly, but then after rebooting the containers all the workflow modules are disabled again. The mounted config is still correct, and workflows and action are still enabled as expected.

Following the steps below I was able to reproduce the issue:

```
Start VM Fedora 40 x64
vCPU/s:
1 vCPU
RAM:
2048.00 MB
Storage:
50 GB NVMe

sudo dnf -y install dnf-plugins-core
sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
sudo dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
systemctl start docker

git clone https://github.com/MISP/misp-docker.git
cd misp-docker
mv template.env .env
set base_url env to IP of VM

setenforce 0 #Disable SELinux
#remove auth requirements redis, this was giving me grief

docker compose up -d

#go into settings
#enable workflows and actions
#enable all workflow modules

docker compose down

docker compose up -d

#workflow modules are disabled again
```

I hope my description is clear, otherwise I am happy to further clarify!

**Comment by zebaz** [comment]
Experiencing the same issues - was really excited about implementing workflows since it potentially can alleviate a lot of custom patches to our MISP instance. Hoping to see a fix and happy to assist in debugging if needed.

**Comment by ostefano** [comment]
@zebaz can you track down what settings are modified when workflows modules are enabled?

**Comment by ostefano** [comment]
I have enabled workflows and action services by default.

Once this succeeds, pull again: https://github.com/MISP/misp-docker/actions/runs/10529748694
