### ISSUE TITLE
latest Tags in docker-compose.yml are hardcoded / Audit Log capabilities for misp-core

### ISSUE THREAD

**Issue by joe-speedboat** [MISP/misp-docker#114]
Hi

I found two minor misconfiguration in `docker-compose.yml`

- Missing Capabilities for misp-core container, which prevents writing auditlogs
- "latest" tags where hard code in docker image url, but should be tag variables from env

#113   Is the pull request for this two config changes

thanks for merging

**Comment by ostefano** [comment]
Can you split the issues/PRs? I would merge the missing capability faster than the second one.

**Comment by joe-speedboat** [comment]
Splitted:

#117 for TAGS
#116 for Caps

**Comment by ostefano** [comment]
Replied to both PRs.

Thanks for the contribution!

**Comment by joe-speedboat** [comment]
thanks
