### ISSUE TITLE
misp-core-1 Container Stuck with Errors During MISP Installation Using Docker Compose

### ISSUE THREAD

**Issue by NattawatPisetsalasai** [MISP/misp-docker#118]
Hello,

I'm trying to install MISP using Docker and followed the instructions. 
I copied template.env to .env and executed docker-compose pull, followed by docker-compose up.

While most services start up fine, the misp-core-1 container keeps producing the following messages:

misp-core-1     | 2024-08-16 08:05:02,985 INFO spawned: 'cache_04' with pid 2313
misp-core-1     | 2024-08-16 08:05:03,001 WARN exited: cache_03 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:05:03,063 INFO spawned: 'cache_03' with pid 2318
misp-core-1     | 2024-08-16 08:05:03,069 WARN exited: prio_03 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:05:03,237 WARN exited: prio_01 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:05:03,237 WARN exited: prio_02 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:05:03,238 INFO success: default_02 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:05:03,238 INFO success: default_04 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:05:03,239 INFO success: email_02 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:05:03,239 INFO success: email_03 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:05:03,241 INFO success: email_04 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:05:03,241 INFO success: cache_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:05:03,281 INFO spawned: 'prio_01' with pid 2333
misp-core-1     | 2024-08-16 08:05:03,298 INFO spawned: 'prio_02' with pid 2339
misp-core-1     | 2024-08-16 08:05:03,337 INFO spawned: 'prio_03' with pid 2342
misp-core-1     | 2024-08-16 08:05:03,549 INFO success: default_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:05:03,549 INFO success: cache_02 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:05:03,551 WARN exited: default_01 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:05:03,553 INFO spawned: 'default_01' with pid 2361
misp-core-1     | 2024-08-16 08:05:03,640 WARN exited: email_00 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:05:03,641 WARN exited: default_02 (exit status 1; not expected)

.
.
.
.
.

misp-core-1     | 2024-08-16 08:08:40,158 INFO spawned: 'prio_03' with pid 21674
misp-core-1     | 2024-08-16 08:08:40,159 WARN exited: cache_01 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:08:40,177 INFO spawned: 'cache_01' with pid 21679
misp-core-1     | 2024-08-16 08:08:40,252 WARN exited: email_04 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:08:40,254 INFO spawned: 'email_04' with pid 21687
misp-core-1     | 2024-08-16 08:08:40,367 INFO success: default_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,368 INFO success: email_03 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,368 WARN exited: prio_02 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:08:40,375 INFO spawned: 'prio_02' with pid 21694
misp-core-1     | 2024-08-16 08:08:40,556 INFO success: default_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,556 INFO success: email_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,557 WARN exited: cache_00 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:08:40,557 WARN exited: email_00 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:08:40,558 WARN exited: prio_00 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:08:40,599 INFO spawned: 'email_00' with pid 21722
misp-core-1     | 2024-08-16 08:08:40,675 INFO spawned: 'cache_00' with pid 21727
misp-core-1     | 2024-08-16 08:08:40,706 INFO success: cache_02 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,718 INFO spawned: 'prio_00' with pid 21728
misp-core-1     | 2024-08-16 08:08:40,721 INFO success: prio_01 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,721 INFO success: update_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,738 WARN exited: default_03 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:08:40,740 WARN exited: email_02 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:08:40,741 INFO success: default_02 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,775 INFO spawned: 'default_03' with pid 21732
misp-core-1     | 2024-08-16 08:08:40,830 INFO spawned: 'email_02' with pid 21737
misp-core-1     | 2024-08-16 08:08:40,832 INFO success: prio_04 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,925 INFO success: default_04 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,925 INFO success: cache_03 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,926 INFO success: cache_04 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
misp-core-1     | 2024-08-16 08:08:40,975 WARN exited: default_01 (exit status 1; not expected)
misp-core-1     | 2024-08-16 08:08:40,976 WARN exited: cache_02 (exit status 1; not expected)

.
.
.

Does anyone have any idea what might be causing this issue or how I can resolve it?

I'm running Docker version 27.1.2, Docker Compose version v2.28.1 on Kali

Thanks in advance for your help!

**Comment by ostefano** [comment]
Can you try removing the redis container and try again?
Is your user past of the docker group?
Also, can you post the config.php file?
Last thing you can try: update docker following this https://docs.docker.com/engine/install/

**Comment by NattawatPisetsalasai** [comment]
Here are the steps I’ve taken:

1. I commented out the Redis container from the docker-compose.yml file.
2. My user is part of the Docker group.
3. Here is my config.php file

```
<?php
$config = array (
  'debug' => 0,
  'MISP' => 
  array (
    'system_setting_db' => false,
    'python_bin' => '/usr/local/bin/python3',
    'redis_host' => 'redis',
    'attachments_dir' => '/var/www/MISP/app/files',
    'background_jobs' => true,
    'ca_path' => '/etc/ssl/certs/ca-certificates.crt',
    'download_gpg_from_homedir' => false,
    'menu_custom_right_link' => '',
    'menu_custom_right_link_html' => '',
    'online_version_check' => true,
    'osuser' => 'www-data',
    'redis_database' => 13,
    'redis_password' => '',
    'redis_port' => 6379,
    'self_update' => false,
    'tmpdir' => '/var/www/MISP/app/tmp',
    'baseurl' => 'https://localhost',
    'contact' => 'admin@admin.test',
    'email' => 'admin@admin.test',
    'default_attribute_distribution' => 'event',
    'default_event_distribution' => '1',
    'default_event_tag_collection' => 0,
    'delegation' => true,
    'disable_user_login_change' => false,
    'enableEventBlocklisting' => true,
    'enableOrgBlocklisting' => true,
    'event_alert_republish_ban' => true,
    'event_alert_republish_ban_refresh_on_retry' => true,
    'event_alert_republish_ban_threshold' => 120,
    'full_tags_on_event_index' => '1',
    'incoming_tags_disabled_by_default' => false,
    'language' => 'eng',
    'log_auth' => true,
    'log_new_audit' => true,
    'proposals_block_attributes' => false,
    'server_settings_skip_backup_rotate' => false,
    'showCorrelationsOnIndex' => true,
    'showorg' => true,
    'showorgalternate' => false,
    'store_api_access_time' => false,
    'tagging' => true,
    'take_ownership_xml_import' => false,
    'terms_download' => false,
    'unpublishedprivate' => false,
    'user_email_notification_ban' => true,
    'external_baseurl' => 'https://localhost',
    'host_org_id' => 1,
    'log_client_ip' => true,
    'log_user_ips' => true,
    'log_user_ips_authkeys' => true,
    'welcome_text_bottom' => '',
    'welcome_text_top' => '',
  ),
  'GnuPG' => 
  array (
    'binary' => '/usr/bin/gpg',
    'email' => 'admin@admin.test',
    'homedir' => '/var/www/MISP/.gnupg',
    'password' => 'passphrase',
    'onlyencrypted' => false,
  ),
  'SMIME' => 
  array (
    'enabled' => false,
  ),
  'SecureAuth' => 
  array (
    'amount' => 5,
    'expire' => 300,
  ),
  'Security' => 
  array (
    'disable_instance_file_uploads' => false,
    'disable_local_feed_access' => false,
    'rest_client_enable_arbitrary_urls' => false,
    'salt' => 'cQ6w6t0w2XVK-1h#1R!h%mr>80DTs9d<',
    'encryption_key' => '',
    'advanced_authkeys' => true,
    'alert_on_suspicious_logins' => true,
    'check_sec_fetch_site_header' => true,
    'disable_browser_cache' => true,
    'do_not_log_authkeys' => true,
    'log_each_individual_auth_fail' => true,
    'require_password_confirmation' => true,
    'username_in_response_header' => true,
    'rest_client_baseurl' => 'https://localhost',
    'csp_enforce' => true,
    'auth' => 
    array (
    ),
  ),
  'Plugin' => 
  array (
    'Action_services_url' => 'http://misp-modules',
    'Enrichment_services_url' => 'http://misp-modules',
    'Export_services_url' => 'http://misp-modules',
    'Import_services_url' => 'http://misp-modules',
    'ZeroMQ_redis_host' => 'redis',
    'Cortex_services_enable' => false,
    'Enrichment_services_enable' => true,
    'Export_services_enable' => true,
    'Import_services_enable' => true,
    'ZeroMQ_enable' => false,
    'Action_services_enable' => false,
    'Enrichment_hover_enable' => false,
    'Enrichment_hover_popover_only' => false,
    'Enrichment_hover_timeout' => 5,
    'Enrichment_timeout' => 30,
  ),
  'SimpleBackgroundJobs' => 
  array (
    'redis_host' => 'redis',
    'enabled' => true,
    'max_job_history_ttl' => 86400,
    'redis_database' => 1,
    'redis_namespace' => 'background_jobs',
    'redis_password' => '',
    'redis_port' => 6379,
    'supervisor_host' => '127.0.0.1',
    'supervisor_password' => 'supervisor',
    'supervisor_port' => 9001,
    'supervisor_user' => 'supervisor',
  ),
); 
```

4. I updated Docker following the official guide  https://docs.docker.com/engine/install/

Despite these actions, I still encounter the same issue with the misp-core-1 container

**Comment by ostefano** [comment]
Thanks. Can you post the logs in the terminal you get after launching docker-compose? You are not the first person to have this issue, and I would like to get to the bottom of this.

**Comment by ostefano** [comment]
Found the bug. Building a new image here https://github.com/MISP/misp-docker/actions/runs/10420415701

**Comment by NattawatPisetsalasai** [comment]
Now it’s working! Thank you so much for your assistance.
