### ISSUE TITLE
docker-compose.yml is invalid

### ISSUE THREAD

**Issue by gabriel-shtx** [MISP/misp-docker#123]
ERROR: The Compose file './docker-compose.yml' is invalid because: services.misp-core.healthcheck value 'start_interval' does not match any of the regexes: '^x-'

I'm trying to deploy the default configuration, I didn't change any configuration files. And he gives me this error.

I'm running Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1 (Ubunto Server).

Can someone help me?

**Comment by ostefano** [comment]
Update docker following the README instructions, and get additional support on gitter/matrix.
