### ISSUE TITLE
Picking up Root CAs at runtime

### ISSUE THREAD

**Issue by sei-mtrdina** [MISP/misp-docker#129]
Hello,

I am working on a fork that has a use case for additional root certificates, and would like to do this in a way that accepts the root CAs at runtime to avoid baking them into an image. Before I implementing this I wanted to reach out and find out if this was a feature that was of value to upstream, and if so to find out if you have opinions on how you would like to see this implemented.

**Comment by ostefano** [comment]
Check `docker-compose.yml`. If that is not enough for what you need feel free to open a PR and we can take it from there.

**Comment by ostefano** [comment]
@sei-mtrdina I am closing this since there is basic support for this functionality.

Feel free to re-open it once you have some more details about the feature.
