### ISSUE TITLE
HealthCheck Error

### ISSUE THREAD

**Issue by JD-Copeland** [MISP/misp-docker#130]
Get the following error when doing the docker-compose pull

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.misp-core.healthcheck value 'start_interval' does not match any of the regexes: '^x-'

**Comment by ostefano** [comment]
Update docker

**Comment by Jonesckevin** [comment]
Currently on Ubuntu 22.04 and Docker version 27.2.0 and it does not work.

**same Issue:**
services.misp-core.healthcheck value 'start_interval' does not match any of the regexes: '^x-'

Removing the health checks is not a solution based on my attempts.

**Comment by ostefano** [comment]
Update docker following the directions outlined in the readme.

**Comment by Jonesckevin** [comment]
As per the instructions mentioned. 

`docker-compose` fails and `docker compose` wins.

**Comment by ostefano** [comment]
I guess we should update the readme and stop suggesting `docker-compose` at all :)
