### ISSUE TITLE
Redis variables

### ISSUE THREAD

**Issue by net-fall** [MISP/misp-docker#134]
Hello.
I'm trying to deploy MISP in separate podman-systemd units and faced some troubles with .env variables.

**MYSQL** variables are recognized correctly. However, **REDIS** variables are not. It doesn't matter if  the **REDIS_PASSWORD** is set or not, any string in **config.php** inside the **misp-core** container where the Redis password is mentioned has the value `redispassword`. Additionally, the **misp-modules** container log has a string: 
`WARNING - Helpers failed cache.py due to Redis not running or not installed. Helper will be disabled.`
And now my MISP deployment stuck with:
`You have tripped the cross-site request forgery protection of MISP`

**Comment by ostefano** [comment]
Issue 1: REDIS password not showing in the logs or config.php. Just tried and can't reproduce. Here working correclty.

Issue 2: Helper failed etc etc. Fix needed to be committed to MISP-modules (didn't support redis passwords before). If you use at least version 2.4.196 the issue should not be there.

Issue 3: cross-site etc etc. Not related to the docker image.

Closing the issue.
You are welcome to ask for additional support on gitter/matrix channels.

**Comment by wmax641** [comment]
@urfin00djuce This bit here [entrypoint.sh](https://github.com/MISP/misp-docker/blob/24690cafe54ff4961d38dacb7f9c9a805c82a607/core/files/entrypoint.sh#L17) sets the default Redis password if a particular environment variable is not set at the time of container entrypoint. This would be the root of your issue.

The (Cake)PHP used by MISP in this container, will use PHP sessions, and store session details in Redis.
However, if Redis hostname/password is improperly configured (via the above environment variables) then it will fail to find any stored sessions. It consequently always fails CSRF validation due to client's presented session token always differing from the EMPTY session token it finds from failed Redis lookups.

**Comment by ostefano** [comment]
I see, however since this docker image enforces using a password for redis I am not sure whether there is anything we need to fix, besides making sure the password is set?

**Comment by net-fall** [comment]
@ostefano You are right. I compared my current deployment with the previous installation I made a couple of months ago and realized I missed the `--requirepass` argument. Here's what my `.container` file looks like now:

```
[Container]
ContainerName=misp-redis
Image=docker.io/valkey/valkey:7.2
Network=misp-net
Volume=redis_data:/data
PodmanArgs=--network-alias redis
Exec=--requirepass ${REDIS_PASSWORD}
EnvironmentFile=ENV_PATH
```

In the **misp-core** container logs, I can see the Redis password is correctly referenced using the REDIS_PASSWORD variable.

@wmax641 I realize my problem is somehow related to Redis. As I mentioned before, my previous installation with **podman-systemd** was successful, but upgrading the **misp-core** and **misp-modules** containers to the latest version caused the same CSRF issue. I'll try to debug this further.

**Comment by ostefano** [comment]
@urfin00djuce since podman is a widely used alternative, would you consider opening a PR with some documentations or any other files required for it to work? Thinking of `container` for example, not sure there are others.

**Comment by net-fall** [comment]
@ostefano I can provide the `container`, `volume`, and `network` files with comments. However, please note that the current setup is not functioning properly.

**Comment by ostefano** [comment]
We can wait for the issues to be fixed as I wouldn't know how to solve them :)

**Comment by 0kn0t0K** [comment]
Had a similar issue,  

In configs/config.php replace "redis" in  line:  tcp://redis:6379?auth=redispassword

with the name of the container

 e.g tcp://misp-docker-redis-1:6379?auth=redispassword

docker compose up -d --build

**Comment by ostefano** [comment]
There is an env var for that (`$REDIS_HOST`)

**Comment by 0kn0t0K** [comment]
> There is an env var for that (`$REDIS_HOST`)

Thank you,  have now implemented this using .env

**Comment by net-fall** [comment]
Just in case anyone's curious, I figured out my Redis problem.
You need to put the link to the variable file in the `[Container]` section so the variables work inside the container.
And, to use those variables in the shell, you should also put the link in the `[Service]` section.
