### ISSUE TITLE
MISP Workflow module requires Redis NOAUTH

### ISSUE THREAD

**Issue by DaanWillems** [MISP/misp-docker#139]
Hello,

I updated to check whether the fix for #111 was working, however the new version of the core image has redis password requirements built in. This means that in my deployment I also have to start with Redis with a password set. 

However it seems this breaks the workflow system:
![image](https://github.com/user-attachments/assets/b4d9d9ec-f136-4dea-b1c3-84b20e20c4e3)

As the redis connection options are built into the entrypoint scripts of the container I cannot simply disable them.

**Comment by ostefano** [comment]
It means you need to restart REDIS because redis is itself needs to be configured with a password.

In other words, both MISP AND Redis containers need to be configured to use a password not just MISP (actually, also MISP-modules).

**Comment by DaanWillems** [comment]
Hello,

Thanks for you reply, I did reboot all containers before posting but the error persisted. 

However killing the modules containers and restarting it separately did fix this issue. Not sure why my initial restart did not work, but must have been some mistake on my end. Thanks for the assistance!
