### ISSUE TITLE
misp modules container cannot be contacted - connection refused

### ISSUE THREAD

**Issue by mamema** [MISP/misp-docker#14]
setup the environment according to the information available here.
can contact the misp-modules container exposed port 6666 via telnet
but in misp-core diagnostics i get "connection refused"

Enrichment module system…Connection refused
Import module system…Connection refused
Export module system…Connection refused
Cortex module system…System not enabled

i even tried to use a modified container with the entrypoint misp-modules -l 0.0.0.0 -s 
with no avail

**Comment by ostefano** [comment]
Would help to see the logs of `docker-compose up`.

Also, since the issue seems to be related to how you use the image rather than the image itself, I would ask for support on Gitter.
