### ISSUE TITLE
Supports Mysql connection with ssl_key, ssl_cert and ssl_ca

### ISSUE THREAD

**Issue by srPuebla** [MISP/misp-docker#140]
Hi,

Could be posible to add supports to "ssl_key", "ssl_cert" and "ssl_ca" for Mysql connector?

I mean. On MISP, at file MysqlExtendedLogging.php you have the next configuration:

```

/**
 * Connects to the database using options in the given configuration array.
 *
 * MySQL supports a few additional options that other drivers do not:
 *
 * - `unix_socket` Set to the path of the MySQL sock file. Can be used in place
 *   of host + port.
 * - `ssl_key` SSL key file for connecting via SSL. Must be combined with `ssl_cert`.
 * - `ssl_cert` The SSL certificate to use when connecting via SSL. Must be
 *   combined with `ssl_key`.
 * - `ssl_ca` The certificate authority for SSL connections.
 *
 * @return bool True if the database could be connected, else false
 * @throws MissingConnectionException
 */
	public function connect() {
		$config = $this->config;
		$this->connected = false;

		$flags = $config['flags'] + array(
			PDO::ATTR_PERSISTENT => $config['persistent'],
			PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true,
			PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
		);

		if (!empty($config['encoding'])) {
			$flags[PDO::MYSQL_ATTR_INIT_COMMAND] = 'SET NAMES ' . $config['encoding'];
		}
		if (!empty($config['ssl_key']) && !empty($config['ssl_cert'])) {
			$flags[PDO::MYSQL_ATTR_SSL_KEY] = $config['ssl_key'];
			$flags[PDO::MYSQL_ATTR_SSL_CERT] = $config['ssl_cert'];
		}
		if (!empty($config['ssl_ca'])) {
			$flags[PDO::MYSQL_ATTR_SSL_CA] = $config['ssl_ca'];
		}
```

And in database.php you will have:
```

class DATABASE_CONFIG {

	public $default = array(
		'datasource' => 'Database/Mysql',
		//'datasource' => 'Database/Postgres',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'db login',
		'port' => 3306, // MySQL & MariaDB
		//'port' => 5432, // PostgreSQL
		'password' => 'db password',
		'database' => 'misp',
		'prefix' => '',
		'encoding' => 'utf8',
		**'ssl_key' => '/opt/misp/mispmysql.key',
		'ssl_cert' => '/opt/misp/mispmysql.cert',
		'ssl_ca' => '/opt/misp/mispmysql.ca',**
	);
}

```

**Comment by ostefano** [comment]
Yes, that would make sense 👍

No plan to work on it myself, but happy to review PRs in this direction and merge them.

**Comment by ostefano** [comment]
Oh, I noticed that this is not even supported in MISP.

I will close this then. There is no chance we can add it if MISP does not support it.

Feel free to re-open the issue in the right project.

**Comment by srPuebla** [comment]
> Oh, I noticed that this is not even supported in MISP.
> 
> I will close this then. There is no chance we can add it if MISP does not support it.
> 
> Feel free to re-open the issue in the right project.

One question Ostefano. 
Where did you find that MISP doesnt support this feature? I have just asked directly to MISP project if they supports this or not on [https://github.com/MISP/MISP/issues/9917](https://github.com/MISP/MISP/issues/9917)

Anyway, i can see on code at file [https://github.com/MISP/MISP/blob/7749e8f305ea4bc269ad3eb33aa93e7e231b6eb5/app/Model/Datasource/Database/MysqlExtendedLogging.php](https://github.com/MISP/MISP/blob/7749e8f305ea4bc269ad3eb33aa93e7e231b6eb5/app/Model/Datasource/Database/MysqlExtendedLogging.php) that you can connect the Mysql with ssl. "MySQL supports a few additional options that other drivers do not"

Besides i asked to chatgpt and he answer me that MISP support this kind of connection. 

When possible tell me!

Thanks!

**Comment by ostefano** [comment]
I checked the default configuration file and documentation https://github.com/MISP/MISP/blob/2.4/app/Config/database.default.php and there is no mention of ssl so I inferred that it is not a tested feature.

Feel free to test it, and if successful, feel free to open a pull request to add support for it to misp-docker.
