### ISSUE TITLE
Issue with recent MISP release

### ISSUE THREAD

**Issue by blazingussenterprise** [MISP/misp-docker#141]
Hi,

I've been trying to get the recent MISP release to work, but when I clone the master repo and change the template.env to .env and assign a baseurl, while keeping the rest of the settings/compose file same, the misp-core container is always unhealthy, any reason why this is happened? Did something break after the last commit?
`CONTAINER ID   IMAGE                                          COMMAND                  CREATED         STATUS                      PORTS                                                                      NAMES
dad4249edd3c   ghcr.io/misp/misp-docker/misp-core:latest      "/entrypoint.sh"         3 minutes ago   Up 35 seconds (unhealthy)   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   misp-docker-misp-core-1
bfe679bc1924   ghcr.io/misp/misp-docker/misp-modules:latest   "/usr/local/bin/misp…"   3 minutes ago   Up 3 minutes                                                                                           misp-docker-misp-modules-1
82c928cafbf0   mariadb:10.11                                  "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes (healthy)      3306/tcp                                                                   misp-docker-db-1
ba4a8a5bc092   valkey/valkey:7.2                              "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes (healthy)      6379/tcp                                                                   misp-docker-redis-1
2f68c67fc31a   ixdotai/smtp                                   "/bin/entrypoint.sh …"   3 minutes ago   Up 3 minutes                25/tcp                                                                     misp-docker-mail-1`

Please help!

Thanks.

**Comment by ostefano** [comment]
From clean repo, I get this:

```
{
  "Status": "healthy",
  "FailingStreak": 0,
  "Log": [
    {
      "Start": "2024-09-05T15:24:03.515897507Z",
      "End": "2024-09-05T15:24:03.576601049Z",
      "ExitCode": 0,
      "Output": ""
    },
    {
      "Start": "2024-09-05T15:24:05.578253925Z",
      "End": "2024-09-05T15:24:05.627159758Z",
      "ExitCode": 0,
      "Output": ""
    },
    {
      "Start": "2024-09-05T15:24:07.628368218Z",
      "End": "2024-09-05T15:24:07.686781426Z",
      "ExitCode": 0,
      "Output": ""
    },
    {
      "Start": "2024-09-05T15:24:09.687335344Z",
      "End": "2024-09-05T15:24:09.746083885Z",
      "ExitCode": 0,
      "Output": ""
    },
    {
      "Start": "2024-09-05T15:24:11.747249178Z",
      "End": "2024-09-05T15:24:11.81648647Z",
      "ExitCode": 0,
      "Output": ""
    }
  ]
}
```

I am closing the issue.
If you have more issues feel free to ask for help on gitter/matrix chan.
