### ISSUE TITLE
Nginx LDAP

### ISSUE THREAD

**Issue by net-fall** [MISP/misp-docker#147]
There is a [link](https://github.com/MISP/misp-docker/blob/beb62e4dcc90f3db1bd07f7312de033422dae6b9/template.env#L125C1-L125C123) in `template.env` to LDAP authentication for Apache. But it's not relevant for Nginx. Any plans for LDAP and Nginx integration?

**Comment by ostefano** [comment]
No plan and out of scope for this project. The link was provided by one of the contributors (@arvchristos ) as a pointer to further details re the feature.

**Comment by arteta22000** [comment]
Hello @ostefano , so if we need LDAP authentication on the webui, we can't use your docker images? because it requires an apache instead of a nginx, right ?

**Comment by ostefano** [comment]
Not correct.

LDAP authentication works, ask the matrix/gitter channel, many users are using it.

**Comment by arteta22000** [comment]
Oh ok, there's something I don't understand.
So when we activate the ldap block in the .env file, it sets up in configure.php for MISP but also the nginx side? it adds a nginx LDAP block to have the REMOTE_USER "header"?

![image](https://github.com/user-attachments/assets/654c8e11-58ae-4dd4-81a3-7d69679aa3b1)

**Comment by ostefano** [comment]
I honestly have no idea, I am not the one who implemented the LDAP part.
As I said, ask the matrix/gitter channel.

**Comment by net-fall** [comment]
Hi @arteta22000
Could you please share the solution if you get it?
I saw **Kagee's** comment too. And the only solution that came to my mind is to add a container from the project [nginx-ldap-auth](https://github.com/nginxinc/nginx-ldap-auth) to the deployment. But I haven't moved in that direction yet

**Comment by arteta22000** [comment]
yes, or use apache instead of nginx and set up LDAP authentication in an apache conf file with info from the .env file?
