### ISSUE TITLE
Add X-Frame-Options

### ISSUE THREAD

**Issue by Diogo-Rego** [MISP/misp-docker#149]
* Where do I add or configure X-Frame-Options in MISP

![image](https://github.com/user-attachments/assets/64620d4e-1fb1-4b3e-a438-6d503bc39b5e)
![image](https://github.com/user-attachments/assets/13d47642-7455-4867-a8f3-825805cb43ed)

**Comment by ostefano** [comment]
This is not related to misp-docker. Open the same issue in MISP or, better, ask in the gitter/matrix channel

**Comment by Diogo-Rego** [comment]
Confirm PR about X-Frame
https://github.com/MISP/misp-docker/pull/159
