### ISSUE TITLE
Scheduled Tasks doesnt work

### ISSUE THREAD

**Issue by palcica** [MISP/misp-docker#152]
I've established a scheduled task with a one-hour recurrence interval, however, it is not initiating. Are there any prerequisite configurations beyond defining the date and hourly pattern?

**Comment by ostefano** [comment]
Ask matrix/gitter for support. Unlikely to be MISP docker related.

**Comment by palcica** [comment]
how it is not related to MISP or docker, scheduled tasks are in menu in MISP. :) You just set a time and date for pull or push.

**Comment by ostefano** [comment]
This is the MISP-docker GitHub project, not the MISP GitHub project.

You want to open the issue here: https://github.com/MISP/MISP/issues
