### ISSUE TITLE
MISP Env `OIDC_ENABLE=true`

### ISSUE THREAD

**Issue by Diogo-Rego** [MISP/misp-docker#158]
MISP Env `OIDC_ENABLE=true` not working correctly, where when doing `OIDC_ENABLE=true` and then `OIDC_ENABLE=false` it still remains with `OIDC_ENABLE=true`

**Comment by ostefano** [comment]
I am not surprised by this, I see rarely testing flipping on/off a new functionality.

For the time being, just remove the config.php file and let the container recreate it.

Obviously I would totally welcome PRs fixing this specific behavior.

**Comment by Diogo-Rego** [comment]
@ostefano 
Can we accept this PR https://github.com/MISP/misp-docker/pull/148 now so I can fix this bug?

**Comment by ostefano** [comment]
@Diogo-Rego done

**Comment by Diogo-Rego** [comment]
@ostefano confirm this PR https://github.com/MISP/misp-docker/pull/161

**Comment by ostefano** [comment]
Added comment

**Comment by Diogo-Rego** [comment]
> Added comment

@ostefano confirm again
