### ISSUE TITLE
HSTS Missing From HTTPS Server (RFC 6797)

### ISSUE THREAD

**Issue by Tux-Panik** [MISP/misp-docker#166]
According to a vulnerability scan I ran on the application, while it was exposed without any filtering, the scan engine raised the following **CVSS 5.8** weakness: **HSTS Missing From HTTPS Server (RFC 6797)**

Issue:
_The remote web server is not enforcing HSTS, as defined by RFC 6797. HSTS is an optional response header that can be configured on the server to instruct the browser to only communicate via HTTPS. The lack of HSTS allows downgrade attacks, SSL-stripping man-in-the-middle attacks, and weakens cookie-hijacking protections._
[https://tools.ietf.org/html/rfc6797](https://tools.ietf.org/html/rfc6797)

Solution :
_Configure the remote web server to use HSTS._

I found the following documentation, but so far the few tests I did were not concluant:
[https://www.ephost.com/account/index.php/knowledgebase/221/How-to-enable-HSTS-and-Security-Response-Headers.html](https://www.ephost.com/account/index.php/knowledgebase/221/How-to-enable-HSTS-and-Security-Response-Headers.html)

Any idea to avoid this issue?
Regards,

**Comment by ostefano** [comment]
Try setting the HSTS_MAX_AGE= variable.

**Comment by Tux-Panik** [comment]
Thanks @ostefano,
Is it a new/recent setting?

**Comment by ostefano** [comment]
Correct

**Comment by Tux-Panik** [comment]
Good to know.
Thus, I'll upgrade to latest image first and then will enable the setting.
Thanks a lot!

**Comment by Tux-Panik** [comment]
I do confirm that this setting fixes the vulnerability after upgrade.
Thanks for your support.
Regards,
