### ISSUE TITLE
Error: Argument 1 passed to Attribute::__construct() must be of the type int, array given

### ISSUE THREAD

**Issue by dgujarathi** [MISP/misp-docker#169]
After login for all modules where Attribute model is used I keep getting this error
Error: Argument 1 passed to Attribute::__construct() must be of the type int, array given

Also the docker logs keep showing it repetitively
Error: Argument 1 passed to Attribute::__construct() must be of the type int, array given
#0 [internal function]: Attribute->__construct()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#5 /var/www/MISP/app/Console/Command/AppShell.php(42): Shell->initialize()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): AppShell->initialize()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#9 {main}

**Comment by ostefano** [comment]
This is a MISP big not a MISP-docker bug. Please open the issue in the right project.

**Comment by ostefano** [comment]
Even better, ask Gitter/Matrix channel for help triaging this
