### ISSUE TITLE
BUG FIX: Proxy Settings refusing to work correctly with http proxy

### ISSUE THREAD

**Issue by c00k3** [MISP/misp-docker#173]
Hello there! 

For many versions, this has never worked for us. My company use a corporate SQUID proxy and under a "http://[host]:[port]" configuration with no auth required, it fails and also breaks the Diagnostics page in https://<our_instance>.com/servers/serverSettings/diagnostics

My fix has been to amend the **CurlClient.php** file, located in **/var/www/MISP/app/lib/Tools/** - declaring the option for:
`CURLOPT_PROXYPORT => '<the_port_we_use>'`

This I place within the following section:

private function generateDefaultOptions()
{
    $options = [
        CURLOPT_FOLLOWLOCATION => true // Allows to follow redirect
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_RETURNTRANSFER => true, // Should cURL return or print out the data? (true = return, false = print)
        CURLOPT_HEADER => false, // Include header in result?
        CURLOPT_TIMEOUT => $this->timeout, // Timeout in seconds
        CURLOPT_PROTOCOLS => CURLPROTO_HTTPS | CURLPROTO_HTTP, // be sure that only HTTP and HTTPS protocols are enabled
        CURLOPT_PROXYPORT => '<the_port_we_use>'
    ];

Just wondering if this could be assessed because whenever the container is restarted or updated I have to run my script and pray that it still works to fix the bug.

Many thanks in advance!

**Comment by ostefano** [comment]
I don't think this is the right place since it is not related to the docker image.

Ask for help in the MISP/Support gitter/matrix channel.

**Comment by c00k3** [comment]
@ostefano - Do you have a link?
Thanks!

**Comment by ostefano** [comment]
@c00k3 https://www.misp-project.org/support/
