### ISSUE TITLE
"MISP.org" configuration setting in MISP core/files/configure_misp.sh

### ISSUE THREAD

**Issue by escamudo** [MISP/misp-docker#178]
Is it possible to also populate dynamically the "MISP.org" setting based on the docker ${ADMIN_ORG} environment variable? This would streamline configuration by automatically setting the organization name from the environment variable.

For example, the following command could be added to ***core/files/configure_misp.sh***:

```bash
sudo -u www-data /var/www/MISP/app/Console/cake Admin setSetting -q "MISP.org" "${ADMIN_ORG}"
´´´

**Comment by ostefano** [comment]
There might be a race because the org id is set based on the org name, but if done properly I see no issue on this 👍
