### ISSUE TITLE
Issues when using custom misp-object templates

### ISSUE THREAD

**Issue by EthanGoodman** [MISP/misp-docker#179]
Right now, I am trying to get an object template inside of the /var/www/MISP/app/files/misp-objects/objects directory. I decided to mount my object template with a docker volume inside of a docker compose file with this: 

"/path/to/my/object-template:/var/www/MISP/app/files/misp-objects/objects/new-object-template"

This is not seeming to work and actually when I ran this:
 "/path/to/my/object-template:/var/www/MISP/app/files/misp-objects/objects", 
every folder in the objects directory mounted to my object template folder on my host machine. Not sure what is going on here, but I have about 8 object templates specific to my use that I need to get into MISP. Each object template I need is pretty similar, but different enough to need a different template. I have a feed pulling data from somewhere else and need these objects to contextualize the data.

**Comment by ostefano** [comment]
As discussed on Gitter the issue of using MISP custom objects has nothing to do with the "inverted path" issue, and we should first focus on properly handling the former rather than looking at the symptom.

**Comment by EthanGoodman** [comment]
Okay I see. So is there anything I should do?

**Comment by ostefano** [comment]
Can you share the object template?

**Comment by EthanGoodman** [comment]
This is one of them:
{
    "description": "Names of every group/channel telegram analyzed",
    "meta-category": "misc",
    "name": "Group names",
    "uuid": "bf90a06a-5f3b-40af-96e1-0839512381d3",
    "version": 1,
    "attributes": {
        "group-name": {
            "description": "Name of one of the groups analyzed",
            "disable_correlation": true,
            "misp-attribute": "text"
        }
    }
}

Sorry for the weird format I cant figure out why it wont keep indents

**Comment by ostefano** [comment]
The `files` directory is already mapped on the host system. 

Just copy the template in the `files/misp-objects` directory and it should work.

It should also persist objects restarts because the directory is shared with the host.
If there is any process internal to MISP that overwrites the content at each restart or update just copy the template at each restart.
