### ISSUE TITLE
MISP.footer_logo Problem: Enabling it Causes Web UI to Become Unresponsive

### ISSUE THREAD

**Issue by TGeeSec** [MISP/misp-docker#187]
After enabling the MISP.footer_logo within the web UI settings, the MISP web UI became unresponsive, displaying only a black bar at the top without any text. The rest of the interface fails to load, and access to other sections is missing.

Probably this problem is not specific to the Docker version, but rather to MISP, so maybe the issue is wrong here?

Steps to Reproduce:
1. Change the MISP.footer_logo setting to true.
2. Refresh the site.

Solution: 
Disable or reset the MISP.footer_logo setting via the console using and restart the docker. 

`app/Console/cake Admin setSetting MISP.footer_logo "" --force`

**Comment by ostefano** [comment]
Yup, please open the issue in the MISP project
