### ISSUE TITLE
Adjust php-fpm pool: enable the increase of maximum number of processes

### ISSUE THREAD

**Issue by capile** [MISP/misp-docker#190]
There are no configuration settings to adjust the php-fpm pool file `/etc/php/8.2/fpm/pool.d/www.conf`. At least the `pm.max_children` should be set (defaults to 5).

Increasing this at the `customize_misp.sh` script will require an additional php-fpm restart.

**Comment by ostefano** [comment]
There is already a group of PHP vars. Just add it in there 👍
