### ISSUE TITLE
Blocking issue when using oauth module

### ISSUE THREAD

**Issue by fastfire** [MISP/misp-docker#193]
I would like to point out that using the module to manage authentication with oauth (available at the link https://github.com/MISP/MISP/blob/af4e248690b05e0d319c87ef46ae6313d76933a1/app/Plugin/OidcAuth/README.md) does not seem possible, since running the module installation command `php composer.phar require jumbojett/openid-connect-php` returns the following error:

```
root@misp01:/var/lib/docker/overlay2/fbcb917a46e8eb4cce7f58ff66192298a4a56de2a55bff51f9c8b1656c22f880/merged/var/www/MISP/app# php composer.phar require jumbojett/openid-connect-php
Command 'php' not found, but can be installed with:
apt install php-cli     # version 2:8.1+92ubuntu1, or
apt install php8.1-cli  # version 8.1.2-1ubuntu2.19
```

By installing the php-cli package you can run the command, but it reports problems with the version of php in use.

This appears to be related to the contents of composer.json, which states:

`"php": ">=7.2.0,<8.0.0",`

while the php version in use on the system is 8.1.2.

In addition, the installation requires some php modules (e.g. curl, xml, zip,...). By manually installing the individual modules, you get to the situation of being able to install the oauth module, but access to the platform becomes unavailable, indicating the following error:

`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0".`

**Comment by ostefano** [comment]
Interesting, not that this is a bug with MISP itself since the version constraint is part of the 2.5 release. I will investigate this, but I would also create an issue on the MISP project.

**Comment by ostefano** [comment]
@fastfire you are looking at the wrong composer. This is the correct one: https://github.com/MISP/MISP/blob/2.5/app/composer.json

And the correct dependency is `jakub-onderka/openid-connect-php` which is installed inside the image.

I will close this.
