### ISSUE TITLE
Disable container DB MISP

### ISSUE THREAD

**Issue by nikollas-liv** [MISP/misp-docker#196]
Hello guys. 

I use the project misp with container, but for storage the data I use the mysql in AWS RDS.
I would like disable the db container, why I'm not use this container, but always that I try comment in yaml (configuration db container), and my webpage appear 504 error. Can you help me?

**Comment by ostefano** [comment]
I can't help, but you can look for more support in the gitter/matrix channels.

**Comment by HugeekMcGill** [comment]
@nikollas-liv from my understanding, it needs to be SQL DB. The DB doesn't need to be at the same location has the misp container but needs to be reachable.

gitter would be the best place to ask those question.

**Comment by nikollas-liv** [comment]
So, with mysql is working, but i want to remove the db container to reduce cpu and mem usage.
