### ISSUE TITLE
MISP-Docker version 2.5.3

### ISSUE THREAD

**Issue by HugeekMcGill** [MISP/misp-docker#200]
Hi,

what is the timeline for misp-docker version 2.5.3 ?

**Comment by ostefano** [comment]
Feel free to open a PR on template.env and I'll merge right away (that will trigger a new release, untested but still). Otherwise sometime between tomorrow and x-mas.

**Comment by ostefano** [comment]
Done

**Comment by HugeekMcGill** [comment]
Thanks, sorry for the delay
