### ISSUE TITLE
HTTP authentication header

### ISSUE THREAD

**Issue by meganAndree** [MISP/misp-docker#23]
I am using Splunk SOAR to POST an event tag to MISP.  I have MISP docker configured on an AWS server, but something is prohibiting it from receiving the auth header. This is the error I receive. I have tried changing the httpd file to include SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1, but that has not worked. Any help would be great. 

'post_data_1'  on asset 'misp api' completed with status: 'failed'. Action Info: Size : 709 bytes : [{"app_name":"HTTP","asset_name":"misp api","param":{"context": {"guid": "***************", "artifact_id": 0, "parent_action_run": []}, "headers": "{\n\"Accept\": \"application/json\",\n\"Content-type\": \"application/json\"\n}", "location": "addTag/****", "verify_certificate": false},"status":"failed","message":"Error from server. Status Code: 403 Data from server: {\"name\":\"Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.\",\"message\":\"Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.\",\"url\":\"\\/events\\/addTag\\/****\\/****\"}"}]

**Comment by ostefano** [comment]
I doubt this is an issue with the image itself.

**Comment by meganAndree** [comment]
why did you close this? it is an issue with the image itself, the MISP docker is not allowing the HTTP auth header, and there are many similar issues with the other images https://github.com/MISP/MISP/issues/2424. I am looking for a solution for MISP docker image

**Comment by ostefano** [comment]
The image is currently deployed in multiple settings where authentication is done via API keys and no issue has been reported (using `pymisp`: https://github.com/MISP/PyMISP/blob/main/pymisp/api.py)

**Comment by ostefano** [comment]
Also:

> I have tried changing the httpd file to include SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1, but that has not worked. 

This image does not use apache, so not sure what file/image you tried to modify.
