### ISSUE TITLE
Problem build CANCELED https://raw.githubusercontent.com/MISP/MISP//app/composer.json

### ISSUE THREAD

**Issue by csilva001** [MISP/misp-docker#24]
<img width="826" alt="image" src="https://github.com/MISP/misp-docker/assets/157842060/32e85403-7819-4654-aeba-50cbb2f15f41">

During deployment I got an error https://raw.githubusercontent.com/MISP/MISP//app/composer.json file does not exist

**Comment by ostefano** [comment]
Create the .env file as per README.md
