### ISSUE TITLE
nginx in core failing

### ISSUE THREAD

**Issue by rickimyers** [MISP/misp-docker#27]
nginx seems to fail with the core. 
after following the simple path to get something running. I was unable to connect to the web interface.  After some poking
docker logs -f ID

I found the log appeard to be repeading itself. ( rsync, chown, Init Flipping nginx ) over and over.
connecting to the image with bash and looking at   /var/log/nginx/error.log shows Lots of
[notice] 70257#70257: signal process started
[error] 70257#70257: open() "/run/nginx.pid" failed (2: No such file or directory
[emerg] 70172#70172: socket() [::]:443 failed (97: Address family not supported by protocol)

**Comment by ftoppi** [comment]
Hello,
did you try to set DISABLE_IPV6=true in your .env file?

**Comment by ostefano** [comment]
@rickimyers as @ftoppi suggested, try disable IPV6.

**Comment by rickimyers** [comment]
Thanks that worked. Thank you.
