### ISSUE TITLE
Custom images file in files/img/orgs directory are deleted when MISP core container starts

### ISSUE THREAD

**Issue by vacmf** [MISP/misp-docker#31]
Core Build: v2.4.187

When the docker MISP core service starts, it deletes custom images that had been uploaded via MISP gui. 

An example is organizations logo. MISP saves the images into `/var/www/MISP/app/files/img/orgs/` and the `entrypoint_nginx.sh` set it back to the initial default set of files with `rsync`.

The problem seems to be in the function `update_misp_data_files` in `entrypoint_nginx.sh` that copies the default files in different places including `/var/www/MISP/app/files/img/orgs/` directory by using `rsync`  with the option `--delete`.

See here: 
https://github.com/MISP/misp-docker/blob/fe531d5806165f530f3ce27ec34f334c44187713/core/files/entrypoint_nginx.sh#L151

A fix could be adding `img` to the exception together with `certs`.

However, I noticed that the problem doesn't exist in build v2.4.181 and the difference is in the organizations logos directory that are saved in different paths.
- v2.4.181 -> `/var/www/MISP/app/webroot/img/orgs` 
- v2.4.187 -> `/var/www/MISP/app/files/img/orgs/`

v2.4.181 has no issue because the path is not touched by `rsync`.

Side note, MISP now links organizations logos in the gui by using the `data:image` tag, while before was liking directly the image in the  `img` tag, something changed there but I don't know when.

Given that, might worth having a look at other changes that could relate to the volume mount and entrypoint process.

**EDIT**
Found the change: 

> [fix: [security] Org image upload moved out of webroot](https://github.com/MISP/MISP/commit/9c244eb11514f431e710c94edff1dabf7d59df5c)
> - images will no longer be accessible directly, only via inclusion via file-read/b64 encoding
> - The new store for org images is MISP/app/files/img/orgs - As reported by Yusuke Nakajim
> 

https://github.com/MISP/MISP/blame/0fb58cff4466f2a685063932e99e0ea7bea28280/app/Model/AppModel.php#L4244

**Comment by ostefano** [comment]
I think the solution is similar to this https://github.com/MISP/misp-docker/pull/17 (more context here https://github.com/MISP/misp-docker/issues/16).

Feel free to open a PR fixing this issue in a similar way.

[update]: just noticed that you said the very same thing 😅

**Comment by vacmf** [comment]
Just created the PR for https://github.com/MISP/misp-docker/pull/33 

You are right, somehow I missed the PR about the same issue. :/
