### ISSUE TITLE
OIDC Error: error when parsing role mapping

### ISSUE THREAD

**Issue by thezolin** [MISP/misp-docker#35]
I tried to enable OIDC auth and receive an error message. 

![image](https://github.com/MISP/misp-docker/assets/36763110/9ad1cd14-9277-4999-942f-6267690ca6c1)

On container logs, nothing is mentioned. 

![image](https://github.com/MISP/misp-docker/assets/36763110/cade38ca-e497-4e17-afa8-f59b3e9cf4cd)

I set up my variables under .env file

![image](https://github.com/MISP/misp-docker/assets/36763110/5b733b39-42cd-495a-a38a-fe6e2897af18)

Looking at the docs (https://github.com/MISP/MISP/blob/2.4/app/Plugin/OidcAuth/README.md), is mentioned a installation of a library

cd app
php composer.phar require jakub-onderka/openid-connect-php:1.0.0-rc1
But if I install this I believe will not persist at container restart.

**Comment by ostefano** [comment]
You need to check MISP logs inside the logs directory (on the host).
Installing the library should not be required.

**Comment by pettai** [comment]
Hi,

I wonder if this is the issue:
https://github.com/MISP/misp-docker/blob/887d1b344326187dcd7272a0e0edc5863c1edd4f/core/files/configure_misp.sh#L122

I also have problems getting OIDC correctly configured into `config.php`, during `docker compose up` it says:

`Provided new config is not array, NULL given.`

I've tested the input as the `configure_misp.sh` script runs it (inside the misp docker itself):

```
root@5a3534a3b270:/var/www/MISP# sudo -u www-data php /var/www/MISP/tests/modify_config.php modify "{
            \"OidcAuth\": {
                \"provider_url\": \"https://OIDC-proxy\",
                \"client_id\": \"test_id\",
                \"client_secret\": \"testtesttesttest\",
                \"roles_property\": \"roles\",  
                \"role_mapper\": {"admin": "1","sync-user": "5"},
                \"default_org\": \"ORGNAME\"
            }
        }"
```

I also tested various escaping on the `${OIDC_ROLES_MAPPING}` variable, but I never got the end result in `config.php` to look like described in https://github.com/MISP/MISP/blob/2.4/app/Plugin/OidcAuth/README.md

Perhaps the documentation / example needs to be revisited?
(above example is from https://github.com/MISP/misp-docker/blob/887d1b344326187dcd7272a0e0edc5863c1edd4f/template.env#L100)

**Comment by ostefano** [comment]
Good point.

**Comment by pettai** [comment]
adding `OIDC_ROLES_MAPPING=[]` generates a empty array() in `config.php`, so I suspect the formatting should look like that instead of `OIDC_ROLES_MAPPING={}`

**Comment by ostefano** [comment]
@pettai not sure you are highlighting the actual issue: we are trying to convert json arrays into php associative arrays, so I don't see anything wrong with `OIDC_ROLES_MAPPING={}`.

Unfortunately I don't have time to work on this, but will happily review/merge PRs.

**Comment by ostefano** [comment]
@pettai this is the correct format: `OIDC_ROLES_MAPPING="{\"admin\": \"1\"}"` (valid JSON and quotes escaped).
I will commit an updated description in the template, and close this.
