### ISSUE TITLE
Service 'misp-core' failed to build : Build failed

### ISSUE THREAD

**Issue by TacitTactics** [MISP/misp-docker#37]
I am running in a LXC container on Proxmox. I have tried both a 23.10 and a 22.04 Ubuntu image. Both fail with the same error. 
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Removing intermediate container 2672ecbab5af
 ---> bb2d1770af54
Step 42/53 : COPY --from=python-build /wheels /wheels
COPY failed: stat wheels: file does not exist
ERROR: Service 'misp-core' failed to build : Build failed

**Comment by ostefano** [comment]
Follow the troubleshooting section.

Error is known when trying to build the image with old version of docker.
