### ISSUE TITLE
Custom taxonomies get overwritten on startup

### ISSUE THREAD

**Issue by DaanWillems** [MISP/misp-docker#40]
Core Build: v2.4.188

**Description**
When starting the core container the `files/taxonomies` directory is overwritten by `entrypoint_nginx.sh`. This seems to prevent the user from provisioning custom taxonomies to MISP. 

**Related issues**
#31
#16 
#17 

Can this be fixed by applying a similar exception as used in the related issues, or am I misunderstanding how taxonomies should be provided?

**Comment by ostefano** [comment]
Possibly. I would investigate in the gitter chan and ask some MISP developers.
