### ISSUE TITLE
Uncaught SyntaxError: redeclaration of let keyboardShortcutsManager

### ISSUE THREAD

**Issue by HarimbolaSantatra** [MISP/misp-docker#42]
### Description
On enabling a feed, there's a strange transparent screen showing:
![misp](https://github.com/MISP/misp-docker/assets/62742383/8ad09467-dd27-4da6-ab83-422ec38876ca)

I get the following error on Firefox's console:  

    Uncaught SyntaxError: redeclaration of let keyboardShortcutsManager
        <anonymous> http://veille.eqima.org/js/keyboard-shortcuts.js:1

### Environment
- Firefox version 124.0.2 (64-bit)
- Ubuntu 22.04
- Current master branch of misp-docker
- Using nginx Reverse proxy, but I already tried to set `BASE_URL` to bare IP address and it still doesn't solve the issue.

Notable environment variable:
- DISABLE_IPV6=true
- DISABLE_SSL_REDIRECT=false
- OIDC_ENABLE=false
- LDAP_ENABLE=false

**Comment by ostefano** [comment]
Quite sure this is not related to MISP, and even if it were, this is not a dockerization issue, hence out of scope.

**Comment by HarimbolaSantatra** [comment]
For those who encounter this issue, the error was that my `BASE_URL` was set to http instead of https. ([This](https://github.com/MISP/MISP/issues/6792#issuecomment-749904260) solved it)
