### ISSUE TITLE
Seeking Guidance on Hosting MISP Docker on Azure Container Instances

### ISSUE THREAD

**Issue by moccajoghurt** [MISP/misp-docker#46]
Hello,

I am considering deploying the MISP Docker project on Azure Container Instances but haven't found a clear blueprint or guide for this setup. Has anyone in this community successfully deployed MISP Docker on Azure? If so, could you share any specific configurations, scripts, or strategies you used?

Here are a few specific questions I have:

Are there particular settings or modifications needed in the MISP Docker configuration to optimize it for Azure Container Instances?
Have you encountered any major challenges or limitations while running MISP Docker in this environment?
Is there existing documentation or a deployment guide that you found helpful for this process?
Any feedback or pointers you could provide would be greatly appreciated. Thank you!

**Comment by ostefano** [comment]
Best place to ask is the chat room on Gitter/Matrix 👍

**Comment by ahmed-laajam-maersk** [comment]
Hi @moccajoghurt ! 

I am down this road as well. Did you find a way to deploy MISP in Azure? I am deploying MISP on container instances, and stumbled on hurdles such as having to host the MySQL DB as a seperate resource, but misp-core won't connect to it, although I provided the environment variables of the MySQL when creating the container instance for misp-core.

**Comment by HugeekMcGill** [comment]
I'm going that road soon.

Gitter is a place we can chat about that.

Let's met there
