### ISSUE TITLE
Redis over TLS incompatible due to hardcoded tcp:// in entrypoint

### ISSUE THREAD

**Issue by christianmg99** [MISP/misp-docker#47]
### Context
Currently it is possible to use **Redis over TLS** by appending `tls://` to the `REDIS_FQDN` environment variable, which even if not present in the `template.env` file, is available in the code:
https://github.com/MISP/misp-docker/blob/67d4a0ea326155189c7549b451a1e55a213e2ab4/core/files/configure_misp.sh#L8
Therefore, by setting up this variable in the `.env` file, it is possible to communicate to an external Redis host, which would be via TLS if it's set up as `REDIS_FQDN: "tls://redis.example.com"`
### Error
Unfortunately, the `entrypoint_fpm.sh` file hardcodes the `tcp://` prefix in the FQDN:
https://github.com/MISP/misp-docker/blob/67d4a0ea326155189c7549b451a1e55a213e2ab4/core/files/entrypoint_fpm.sh#L22
Which makes PHP fail to connect to Redis, since the endpoint now looks like `tcp://tls://redis.example.com`.

**Comment by ostefano** [comment]
~~@christianmg99 is `tls://redis.example.com` handled correctly by MISP itself? In other words, what about `configure_misp.sh`? Did you try building the image and looking at diagnostics?~~

Following up in the PR.
