### ISSUE TITLE
Outdated Debian distribution

### ISSUE THREAD

**Issue by christianmg99** [MISP/misp-docker#48]
Both `misp-core` and `misp-modules` have an outdated Debian distribution hardcoded in their `Dockerfile`, forcing use of Debian 11 instead of Debian 12 (Or latest stable release):
https://github.com/MISP/misp-docker/blob/67d4a0ea326155189c7549b451a1e55a213e2ab4/core/Dockerfile#L3
https://github.com/MISP/misp-docker/blob/67d4a0ea326155189c7549b451a1e55a213e2ab4/modules/Dockerfile#L3

**Comment by ostefano** [comment]
There are hard requirements (set by upstream) on which PHP version is to be allowed. Updating the underlying distro might break it. I have approved the build workflow so you can check the logs.

**Comment by christianmg99** [comment]
That's true, sorry I didn't notice :)

**Comment by ostefano** [comment]
I wouldn't abandon this completely. The 'modules' image is fairly independent and it could use some base image refreshing.
