### ISSUE TITLE
ERROR in misp-modules Dockerfile

### ISSUE THREAD

**Issue by AmitKulkarni9** [MISP/misp-docker#51]
looks like there is a mistake in the regex here? 
RUN sed -i s/LoadLibrary\(LOAD_LIB\)/LoadLibrary\(\"\\/usr\\/local\\/lib\\/libfaupl.so\"\)/ \

I am planning to build the individual image and push to ecr. while building the misp-modules image I get below error:

 => ERROR [stage-1 7/7] RUN sed -i '/import sys/a import warnings\nwarnings.warn = lambda *args, **kwargs: None'         /usr/local/bin/misp-modules                                              0.3s 
------
 > [stage-1 7/7] RUN sed -i '/import sys/a import warnings\nwarnings.warn = lambda *args, **kwargs: None'         /usr/local/bin/misp-modules:
0.296 sed: can't read /usr/local/bin/misp-modules: No such file or directory
------
Dockerfile:83
--------------------
  82 |         # Disable (all) warnings raised when using 'future'
  83 | >>>     RUN sed -i '/import sys/a import warnings\nwarnings.warn = lambda *args, **kwargs: None' \
  84 | >>>         /usr/local/bin/misp-modules
  85 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c sed -i '/import sys/a import warnings\\nwarnings.warn = lambda *args, **kwargs: None'         /usr/local/bin/misp-modules" did not complete successfully: exit code: 2

Check the Image in VS Code. 
![image](https://github.com/MISP/misp-docker/assets/21031180/1bedcf14-7374-4ecc-a430-12b4c2d6084a)

**Comment by ostefano** [comment]
No mistake. You need to use a recent version of docker/docker-compose to build. see troubleshooting section and/or ask for guidance in the gitter chan.
