### ISSUE TITLE
Debug Configuration as an Environment Variable

### ISSUE THREAD

**Issue by C0d3rZ3r0** [MISP/misp-docker#57]
There seems to be no way to instantiate a misp-core container with debug mode enabled.

While it is possible to enable debug mode through the UI, it may not always be usable. Consider the case where the container is broken and fails to authenticate despite showing the web UI. In such a case, it's tedious to login into the container to enable debug mode over the shell. It would be convenient if we could respin the container in debug mode amd look at the debug error logs shown on the web UI.

This can be fixed by adding a dedicated "MISP_DEBUG" variable in the .env file.

Obviously, enabling debug mode in a production environment is unsafe, so documentation should appropriately warn of the risk.

**Comment by ostefano** [comment]
Yes, that would be a sensible improvement 👍

**Comment by ostefano** [comment]
@UFOSmuggler turns out this setting accepts a string like 'Debug off'. New system system doesn't seem to digest this. Can you investigate?

**Comment by UFOSmuggler** [comment]
This is added in #71

**Comment by ostefano** [comment]
and merged
