### ISSUE TITLE
CLI-Only Configurations as Environment Variables

### ISSUE THREAD

**Issue by C0d3rZ3r0** [MISP/misp-docker#60]
This is similar to #57, but for other configurations.

Many configurations under Server Settings & Maintenance are marked "[CLI only]" in their descriptions. These cannot be changed via the UI. We again face the same issue described in #57, where one must take a bash shell into the container to configure these settings.

This is tedious and can be avoided if all CLI-only configurations have corresponding environment variables in the .env file which can define the specific settings.

**Comment by ostefano** [comment]
I guess the best way would be to add all variables inside a JSON file that is shared between host and container

**Comment by UFOSmuggler** [comment]
pr #66 semi-addresses this.  

while it does not offer an excellent fix for this issue, it would allow the operator to overmount their own cli_only json files as defined in core/files/etc/misp-docker (or /etc/misp-docker in the container) to make any change they wanted.

happy to take suggestions on modifying the method in this pr to address this issue.

**Comment by UFOSmuggler** [comment]
additionally you could just set any of the cli_only things in the customize_misp.sh script mentioned in the README.

add lines like:

```bash
/var/www/MISP/app/Console/cake admin setSetting Security.salt "blahblahblahblahbigsecret"
```
