### ISSUE TITLE
Enable MISP.system_setting_db by Default for Containerized MISP

### ISSUE THREAD

**Issue by C0d3rZ3r0** [MISP/misp-docker#61]
Configurations are lost if MISP containers are recreated after an update or modification. Due to this, too many things need to be re-configured after updating a running system.
 
The MISP Image should enable the `MISP.system_setting_db` config parameter by default during build.

The other option will be to provide an environment variable in the .env file to affect this parameter, and to set it by default to true in template.env.

`MISP.system_setting_db` is a CLI-only configuration and can't be modified via the web UI. #60 describes this issue further.

**Comment by ostefano** [comment]
That would make sense

**Comment by ostefano** [comment]
Where are all those settings stored? If in a file, would it make sense to share the file with the host (like we do with configs) and have it persisting across restarts?

**Comment by UFOSmuggler** [comment]
pull #66 fixes this by allowing the user to specify whether they want db settings or not.  however i strongly recommend off by default as the settings db really is a second class citizen compared to the config.php file and there are many sharp edges to be found in its operation.  casual users are far less likely to run into issues if using config.php only.
