### ISSUE TITLE
Issue trying to get Authkeys

### ISSUE THREAD

**Issue by TiboJFR** [MISP/misp-docker#62]
Hello,

I am trying to integrate MISP feed into Microsoft Sentinel. For that I need to get an Auth Key for being able to use the misp2Sentinel script.

I'm getting an error 500 when I do that : 
![image](https://github.com/MISP/misp-docker/assets/119405686/9b9771d7-2731-4164-9a50-3671089b65d9)
![image](https://github.com/MISP/misp-docker/assets/119405686/d5c4d66a-dc32-4f29-8a7c-6070ccdc5ba7)

Do you have any clue about the problem ?

**Comment by ostefano** [comment]
This is issue is not related to the docker image. Many deployments use auth keys.
Open an issue in the main MISP project or, better, ask the community in one of the chat channels (gitter/matrix)

**Comment by TiboJFR** [comment]
Hey Stefano,

Thanks for the quick answer. In fact it seems that there is an error with the Redis connection : 
![image](https://github.com/MISP/misp-docker/assets/119405686/5abafc79-d509-4df4-aa69-2322b7973fea)

I just ran the dockerimage as is with no modification, are you sure that there is no docker issue there ?

Thanks,

**Comment by ostefano** [comment]
Can you check whether the redis image has been pulled and the container started?

**Comment by TiboJFR** [comment]
It seems that is is started : 
![image](https://github.com/MISP/misp-docker/assets/119405686/13a2afc1-bca7-4be2-a599-79271e5ec7ff)

**Comment by ostefano** [comment]
Clone repo, pulled images, copied template.env to .env, started containers, and all is well here.

I am going to close this.

<img width="1550" alt="Screenshot 2024-05-17 at 11 26 30" src="https://github.com/MISP/misp-docker/assets/979520/08ca7f79-bf32-48ab-baaf-1114809fe9d4">

**Comment by TiboJFR** [comment]
Ok ty, my bad then I'll restart from the beginning
