### ISSUE TITLE
apply_critical_fixes() in configure_misp.sh turns off actions plugin every time the misp-core container comes up

### ISSUE THREAD

**Issue by UFOSmuggler** [MISP/misp-docker#63]
https://github.com/MISP/misp-docker/blob/master/core/files/configure_misp.sh#L264

I suspect this is forced off so that if the Action_services_url is incorrect, MISP doesn't drop its lunch.  However, it doesn't seem to cause an issue if set to something that doesn't exist.

Perhaps this isn't needed after all?  Otherwise, every time the container comes up we have to edit the config again to turn it back on.

Is there some other reason for this I am not aware of?

**Comment by UFOSmuggler** [comment]
also, i guess setting the enrichment hover stuff is also kinda annoying

**Comment by ostefano** [comment]
I am not against this in principle, but I believe this is also done because until misp-modules are loaded, those settings are not persisted / it is not reliable to set them.

**Comment by UFOSmuggler** [comment]
Perhaps testing for their existence in the database and/or config.php file would be more reasonable than overwriting the users choice?  

If they exist, do nothing, otherwise set to safe defaults?

**Comment by ostefano** [comment]
Yep, that would be a sensible choice. I wonder how all this is affected by `MISP.system_setting_db`. Anyway, I think we should just test removing the setting instructions and see what is the default value on a clean install, and document it (as long as there are no side-effects).
