### ISSUE TITLE
Deployment on server failed

### ISSUE THREAD

**Issue by HugooB** [MISP/misp-docker#7]
Hi there! Great work on dockerizing MISP, much appreciated! I worked with an older version of misp-docker and today updated to this much new version. I've copied the `.env` and edited all the corresponding variables. All containers are running nicely after a `docker compose up`, but I can not access MISP outside of the localhost. Since I can not find the `POSTFIX_RELAY_HOST=relay.fqdn` option that was present in the previous version, I assume that would cause this problem. Any thoughts on how to fix this?

I redacted the IP, but my hostname is:
`HOSTNAME=http://111.222.333.444`

Docker version 24.0.7, build afdd53b

**Comment by ostefano** [comment]
I think those two are separate issues.

So basically you are able to access MISP from the host (where docker is running) but not from an external host?

Did you check that the ports are indeed open from outside (from the client to the host where docker is running)?

**Comment by mselite** [comment]
Hello,

I am facing similar problem. I have deploy MISP on kubenertes server by converting doker-compose file through `kompose`. I have edit `.env` file to set correspond variables and every thing was deployed `(mail, misp-module, redis, db and misp-core)`.
However, I can not access to the admin interface after port forwarding the misp-core on localhost:8080.

Here is the logs of misp-core:
![misp-core logs](https://github.com/MISP/misp-docker/assets/22004301/35b1215b-887c-4b2c-ab25-b18d2eeda0fd)


Is there any additionnal config to do?

Thanks.

**Comment by ostefano** [comment]
@mselite not sure why you are looking to connect on port `8080` since it is not exposed by the container. Nevertheless the errors you are seeing are because the workers are not being able to bootstrap correctly. You could check the logs and/or make sure Redis is running.

I will now close this issue, since the issues you both are facing are deployment issues and not issues with the containerization itself. You are welcome to join the community-supported channels on gitter to discuss these issues further.

**Comment by mselite** [comment]
Hi @ostefano,

You're right about redis, it's been deployed but I haven't created the services. So after creating the services, the misp-core works:
![miso-core](https://github.com/MISP/misp-docker/assets/22004301/74f423b9-cdd2-47dc-ad36-79f9639ec522)

However, setting the redis port `6379` crash the misp-module, see below.
![Capture d’écran du 2023-12-26 11-35-27](https://github.com/MISP/misp-docker/assets/22004301/c530d46f-dc00-44fc-8629-ac44748a17de)

So, when I try to access after portfowarding on 443, I can reach the user login, but it crashes:
![misp-core](https://github.com/MISP/misp-docker/assets/22004301/442c74f5-b336-4cd3-9404-69a66d990844)

Do I need to configure the redis port?
Also, if you can share the link to the gitter channel.

Thanks.

**Comment by ostefano** [comment]
* issues with misp-modules should not affect misp main functionality
* I would check the logs to understand why it is crashing
* understanding which env variables should be set, it is a misp-modules matter so I would check misp-modules resources, e.g., https://misp.github.io/misp-modules/install/
* I would consider starting from scratch, just to be on the safe side
* Gitter channel is listed in the readme, i.e., https://gitter.im/MISP/Docker

**Comment by mselite** [comment]
Okay thanks.

**Comment by deadgirlerg** [comment]
Imposible instalarlo, hasta hace un mes siguiendo unos simples pasos podía instalarlo, ahora solo arroja errores:

ERROR: Service 'misp-core' failed to build : Build failed

Por favor, si alguien pudiera ayudarme a instalarlo, le estaría eternamente agradecida.

**Comment by ostefano** [comment]
Follow the steps outlined in the troubleshooting section, and/or ask for additional support in the Gitter channel (linked above).

Also note that some variable names have been updated so make sure to update your .env file.

**Comment by deadgirlerg** [comment]
Ya resolvi lo anterior... pero ahora me arroja este error. Por favor me podrian ayudar, ya que es para mi proyecto de universidad y de verdad que le he dedicado mucho tiempo a este proyecto como para que me falle ahora ;(

![Captura MISP](https://github.com/MISP/misp-docker/assets/69993924/73b046b6-bfe6-424b-ae87-c69716f58b3b)

**Comment by ostefano** [comment]
Upgrade docker including docker-compose as stated in the Troubleshooting section.

**Comment by deadgirlerg** [comment]
Ostefano un gusto, buenos dias desde Chile, te comento que estoy realizando una instalación desde 0. por ende no podría actualizar nada aun. Es por eso que no entiendo el por que se origina el problema este problema. Lo estoy instalando en Ubuntu Server 22.04, hasta hace 1 mes lo podía instalar sin problema, pero despues de la actualización algo cambio que me impide instalarlo. También instale Docker y docker-compose.

**Comment by ostefano** [comment]
Please follow the instructions to update Docker as stated in the Troubleshooting section (https://docs.docker.com/engine/install/ubuntu/).

You can also try to remove all cached layers as again stated in the Troubleshooting section.

We use many modern features such as build layers, copies between layers etc. You need a recent version of Docker.

**Comment by ostefano** [comment]
Also, please use the Gitter channel to further discuss this issue: https://gitter.im/MISP/Docker

Issues on GitHub are to be used for bugs or feature requests, and your case is neither.

**Comment by deadgirlerg** [comment]
XD Pero si el problema no es Docker, el problema es de ustedes, desde que actualizaron la plataforma hace poco menos de un mes que no se pudo ya instalar... XD

**Comment by ostefano** [comment]
You are always welcome to skip the building phase by using pre-built images via "docker-compose pull".

**Comment by deadgirlerg** [comment]
eres un Dios <3
