### ISSUE TITLE
Custom SSL Cert issue

### ISSUE THREAD

**Issue by benceBalazs** [MISP/misp-docker#72]
Short summary:
- tried installing custom company SSL certs
- set the certs like described in the readme
- misp ignores this every time at the startup and only generates local certs every time

**Comment by ostefano** [comment]
Here it works, you will need to provide more data or logs.
For example, if the certs are ignored, does MISP overwrite them? What is inside the mounted directory?

**Comment by benceBalazs** [comment]
Yeah sorry, was on my phone when I created the issue.

The OS is AlmaLinux.

Here are the files located in /etc/ssl/certs/:

<img width="485" alt="mountsDocker" src="https://github.com/MISP/misp-docker/assets/56939786/4a47effd-2283-4780-9429-3e53cc0b0830">

The config for the mounts:

```
    volumes:
      - "./configs/:/var/www/MISP/app/Config/"
      - "./logs/:/var/www/MISP/app/tmp/logs/"
      - "./files/:/var/www/MISP/app/files/"
      - "./ssl/:/etc/ssl/certs/"
      ...
```

And the partial logs that matter or have to do with SSL:

```
INIT | Initialize NGINX ...
... enabling port 80 redirect
... enabling IPv6 on port 80
... enabling SSL redirect
... enabling port 443
... enabling IPv6 on port 443
... generating new self-signed TLS certificate
Generating a RSA private key
writing new private key to '/etc/nginx/certs/key.pem'
....
INIT | Configure MISP installation ...
MISP | Update CA certificates ...
Updating certificates in /etc/ssl/certs...
129 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.

```

![image](https://github.com/MISP/misp-docker/assets/56939786/3d87934d-bb15-4298-9d8a-ec046b1e2bef)

So the misp-core container just ignores my config and generates a local cert as seen above, even though my custom SSL certs should be valid.

**Comment by ostefano** [comment]
What is inside the local (to the host) directory `./ssl`?

Having said that, I am closing this issue and redirecting this issue to the Gitter/Matrix chat so other users can help you.
This is not an issue with the docker image.
