### ISSUE TITLE
Feature Request: Make SMTP host a configurable option

### ISSUE THREAD

**Issue by damanzanofortra** [MISP/misp-docker#78]
Right now email.php values are hard coded forcing user to use the mail subsystem in docker-compose.
While this is handy for local deployments, it's not suitable when you want to use the image in a different environment like k8s or even docker-compose deployment where another smtp service already exists.

**Comment by damanzanofortra** [comment]
I've submitted https://github.com/MISP/misp-docker/pull/77 for your review.

**Comment by ostefano** [comment]
Still a nit pending (see comment), but will merge it and fix it myself
