### ISSUE TITLE
Writing to a value of 'tmp' clashes with existing /tmp directory

### ISSUE THREAD

**Issue by sy4kford2** [MISP/misp-docker#79]
https://github.com/MISP/misp-docker/blame/5d641c75e4d8f0d68579cc3450b193e7202f8d1b/core/files/entrypoint_nginx.sh#L83C75-L83C75

Hi, we're seeing an issue where if we restart the container, the contents of database.php gets wiped - I suspect it's due to the entrypoint_nginx.sh script being run by supervisord in / - where the /tmp directory already exists.

**Comment by ostefano** [comment]
@sy4kford2 not sure about the correlation, but first try to use the latest version of docker from docker.com
