### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by IAMLED** [MISP/misp-docker#8]
Hi,
I'm running into this issue when building misp.

ERROR: Service 'misp-core' failed to build: COPY failed: stat wheels: file does not exist

How can I resolve this?

**Comment by ostefano** [comment]
Update docker and remove cache before trying again.

**Comment by IAMLED** [comment]
@ostefano Thank you for your prompt response to my issue. 

This is my current docker version
$ docker --version
$ Docker version 24.0.7, build afdd53b

I've removed cache and tried again, but still having the same issue. What else should I attempt?

**Comment by ostefano** [comment]
Prune existing images and containers via "docker system prune -a" and try again

**Comment by ostefano** [comment]
Did you create the '.env' file as per readme, right?

**Comment by IAMLED** [comment]
> Did you create the '.env' file as per readme, right?

Yes

**Comment by IAMLED** [comment]
> Prune existing images and containers via "docker system prune -a" and try again

Done this too, also same issue

**Comment by ostefano** [comment]
Docker compose version?
Host operating system?

If MAC try to change the "Choose file sharing implementation for your containers" to gRPC FUSE

What command are you using to build the image?
Can you attach the logs?

**Comment by ostefano** [comment]
If MAC try to change the "Choose file sharing implementation for your containers" to gRPC FUSE

**Comment by IAMLED** [comment]
> Docker compose version? Host operating system?
> 
> If MAC try to change the "Choose file sharing implementation for your containers" to gRPC FUSE
> 
> What command are you using to build the image? Can you attach the logs?

- docker-compose version 1.25.0, build unknown
- Ubuntu 20.04.6 LTS (Focal Fossa)
- Not MAC
- Command used: docker-compose build
- Logs:

Creating config file /etc/php/7.4/fpm/php.ini with new version
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libnginx-mod-http-image-filter (1.18.0-6.1+deb11u3) ...
Setting up php7.4 (7.4.33-1+deb11u4) ...
Setting up python3-pip (20.3.4-4+deb11u1) ...
Setting up php-fpm (2:7.4+76) ...
Setting up php-gd (2:7.4+76) ...
Setting up nginx-core (1.18.0-6.1+deb11u3) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up php (2:7.4+76) ...
Setting up nginx (1.18.0-6.1+deb11u3) ...
Processing triggers for libc-bin (2.31-13+deb11u7) ...
Processing triggers for ca-certificates (20210119) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Processing triggers for php7.4-cli (7.4.33-1+deb11u4) ...
Processing triggers for php7.4-fpm (7.4.33-1+deb11u4) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Removing intermediate container 46b6f4724373
 ---> 649738978639
Step 42/53 : COPY --from=python-build /wheels /wheels
ERROR: Service 'misp-core' failed to build: COPY failed: stat wheels: file does not exist



That's as much as I can add.

**Comment by ostefano** [comment]
@IAMLED Your docker-compose is quite old, and totally not aligned to the version of Docker you are using.

Try two things:
1) `docker compose` instead of `docker-compose`
2) Update docker using https://docs.docker.com/engine/install/ubuntu/

**Comment by IAMLED** [comment]
@ostefano Thank you so much for your support.
Using `docker compose build` worked for me. 

I truly appreciate your time and effort. 
Thanks
