### ISSUE TITLE
Installing custom wildcard certificate

### ISSUE THREAD

**Issue by alexfuicu** [MISP/misp-docker#85]
Hi,

I am having trouble installing my own certificate (wildcard). I have tried numerous path locations (both in the Linux VM and inside the docker container itself) and guides found over the internet (including the location described in the readme), but nothing worked. Please help me with the exact procedure on how to install the certificate (exact path where it needs to be copied, naming restrictions, extensions etc.). Thanks!

**Comment by ostefano** [comment]
Closing because this is not an issue with the docker image.

For support check gitter (see README)
