### ISSUE TITLE
LDAP authentication - better how-to

### ISSUE THREAD

**Issue by KronwarsCZ** [MISP/misp-docker#86]
Hello everyone!
I'm trying to make MISP work with my local LDAP server and I'm constantly hitting errors on the way. I was wondering if you could explain the process a little bit better? I've read the linked issue in template.env, but I don't understand how to implement this in this project.

My questions are:
Do I need to add some reverse proxy to disable access to MISP directly as mentioned in template.env or is the docker compose ready to just work outside of the box (assuming the config is correct)? If not, what does the disallow direct access to MISP mean? Can I adjust the internal nginx config to be the ldap authenticator?

Right now I'm having the "Column mail cannot be NULL," but the server didn't even ask for my ldap auth, so that's probably what's wrong... 

Thanks for any help!

I'm willing to write a detailed how-to after I make it work 😄

**Comment by ostefano** [comment]
Chat on Gitter/Matrix might be the best place for this type of questions.
