### ISSUE TITLE
Cant 'Docker-compose Pull" 

### ISSUE THREAD

**Issue by davealyn** [MISP/misp-docker#88]
Have followed step by step - but no luck when pulling it or building. 

Any ideas? 

"he Compose file './docker-compose.yml' is invalid because:
services.misp-core.healthcheck value 'start_interval' does not match any of the regexes: '^x-'"

**Comment by ostefano** [comment]
Update Docker.

**Comment by davealyn** [comment]
Didn't work, removed 'start_interval' from compose file - now pulling.

**Comment by ostefano** [comment]
Did you try updating Docker from the docker.com as per README?
That is likely the reason, as nobody else is having this issue.

**Comment by jdgarcia1381** [comment]
Try to use `docker compose` instead of `docker-compose` as mentioned on https://github.com/MISP/misp-docker?tab=readme-ov-file#troubleshooting. `start_inverval` requires docker 25+.
