### ISSUE TITLE
Email Integration Issues

### ISSUE THREAD

**Issue by GeoSegun** [MISP/misp-docker#89]
I have edited the `.env` file to use Google SMTP for email integration. When I try to test whether the email works by creating a new user. It does not send any email notification.
Nevertheless I used a simple python script to check the credentials I used in the .env file and it seems to work.

Is there any solution for this?

**Comment by ostefano** [comment]
What are the logs emitted by the mail container saying?

**Comment by ostefano** [comment]
Also, this is not an issue with the docker image itself.
Please use the Gitter/Matrix channel for additional community support.
