### ISSUE TITLE
nginx 1.18.0 vulnerable and End of life

### ISSUE THREAD

**Issue by HugeekMcGill** [MISP/misp-docker#95]
Hi, 

our vulnerabilities scanners are flagging nginx 1.18.0 as End Of Life and vulnerable.

Is there a plan to migrate the nginx 1.18.0 to latest version ?

I'm working on a local patch for the moment but i would like to know there is plan to use the latest version.

Regards,

**Comment by ostefano** [comment]
See https://github.com/MISP/misp-docker/pull/92

**Comment by HugeekMcGill** [comment]
Awesome, thanks.

I guess it will follow the next misp version ?

**Comment by ostefano** [comment]
Maybe before then.
