### ISSUE TITLE
Feeds Sync Issue

### ISSUE THREAD

**Issue by Moorocks** [MISP/misp-docker#96]
Hello Team, 

We recently started using misp-docker and we are facing an issue with sync of threat feeds. Do we need to configure automatic pulling of feeds?

It looks like the feeds are not being pulled automatically and instead I need to do a manual pull.

If we need to configure pulling of feeds, is it better to configure in GUI or in the docker-compose.yml file?

We migrated from docker to podman recently.

**Comment by ostefano** [comment]
Pulling of feeds should be automatic, and done by the cron job.

Can you try to run the cron job manually and see if the feeds are updated?

**Comment by ostefano** [comment]
Make sure you are not impacted by podman-related issues (see Issues)

**Comment by Moorocks** [comment]
Hey @ostefano , 
It looks like the actual problem is different. The fetch is failing. 
If I look at the logs, i found the below issue:

[error_logs.txt](https://github.com/user-attachments/files/16300997/error_logs.txt)

**Comment by ostefano** [comment]
Well the error is quite explicit as to blaming the server. I will close this issue if nothing new arises.
