### ISSUE TITLE
Docker container resets Server Settings & Maintenance settings after a restart

### ISSUE THREAD

**Issue by yazeedallabadi24** [MISP/misp-docker#98]
- My docker installation run perfectly fine.
- At the ``Server Settings & Maintenance`` section there are a bunch of recommended settings that have ``"Incorrect settings"`` that could be fixed by changing and adding config settings into the **``config.php``** file. 
- The main issue here is that my **``config.php``** file gets reset back to default values after i restart the container (``docker compose down``, then ``docker compose up``) and thus the number of Incorrect Settings returns back at the ``Server Settings & Maintenance`` to how it was before the adjustment.

**Comment by ostefano** [comment]
@UFOSmuggler can you give it a look?

**Comment by ostefano** [comment]
@yazeedallabadi24 did you read the whole section here https://github.com/MISP/misp-docker?tab=readme-ov-file#configuration ?

**Comment by yazeedallabadi24** [comment]
- Yes I have actually. I have tried modifying the `.env` file like `ENABLE_DB_SETTINGS=true` so I can use the DB instead of the config.php for the configurations -> Didn't work out unfortunately as misp-docker creates a new volume everytime it's restarted.
- Additionally, I have tried the `customize_misp.sh` script to try and explicitly modify the configuration settings but likewise the server seems to literally modify the related settings field:value pair within config.php everytime it's restarted causing the same issue to persist.
- It could be me not exactly knowing how to work with these files. But to further explain the issue further my problem is exactly with 4 configuration values within `Server Settings & Maintenance`, and those are in the Plugin category (`Plugin.Enrichment_services_url`, `Plugin.Import_services_url`, `Plugin.Export_services_url`, `Plugin.Action_services_url`) where these are the particular settings that gets reset back to default value (`http://misp-modules`) instead of the value that I explicitly specify (`http://127.0.0.1`).
> <samp> _**Changing these 4 settings alone to the right value of  `http://127.0.0.1` fixes all 500 Incorrect Settings errors at the recommended settings within `Administration`:`Server Settings & Maintenance` tab.**_</samp>

**Comment by ostefano** [comment]
Something is wrong if you need to change `misp-modules` to the localhost address though.

What version of Docker are you using?

**Comment by yazeedallabadi24** [comment]
Docker version 24.0.5
MISP version 2.4.194

**Comment by ostefano** [comment]
Pretty old. Try again with the latest Docker version available.
Also, you can override the misp-modules API endpoint by adding this `MISP_MODULES_FQDN` to the docker compose file

I will close this.

**Comment by yazeedallabadi24** [comment]
Alright, Docker version updated and i tried rerunning the container again.
In what context and where exactly should i put `MISP_MODULES_FQDN` environment variable into the docker compose file. I have added it as part of the environment: section within misp-modules container layer.
Also should I redefine its value since it's default set value is `http://misp-module` as far as I know.

**Comment by ostefano** [comment]
I think you just need to add a new env variable in the misp-core section of the docker compose file.

**Comment by yazeedallabadi24** [comment]
Perfect ! All works as intended now. Thanks a lot for the support and for your time !
